name: CI

on:
  push:
  pull_request:

jobs:
  presubmit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20.19.5
          - 22.12.0
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run presubmit
